spring:
  application:
    name: TaskFlow
  datasource:
    url: jdbc:mysql://localhost:3306/task
    username: root
    password: "000620"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
